routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    $users = App\User::get();

    return view('welcome', ['users' => $users]);
});

Route::get('/profile/{id}', function ($id) {

    $user = App\User::find($id);

    $posts  = $user->posts()
        ->with('category', 'image', 'tags')
        ->withCount('comments')->get();

    $videos = $user->videos()
        ->with('category', 'image', 'tags')
        ->withCount('comments')->get();

    return view('profile', [
        'user'   => $user,
        'posts'  => $posts,
        'videos' => $videos
    ]);
})->name('profile');

Route::get('/level/{id}', function ($id) {

    $level = App\Level::find($id);

    $posts  = $level->posts()
        ->with('category', 'image', 'tags')
        ->withCount('comments')->get();

    $videos = $level->videos()
        ->with('category', 'image', 'tags')
        ->withCount('comments')->get();

    return view('level', [
        'level'  => $level,
        'posts'  => $posts,
        'videos' => $videos
    ]);
})->name('level');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function posts(){
        //Un categoria tiene muchos post
        return $this->hasMany(Post::class);
    }

    public function videos(){
        //Un categoria tiene muchos videos
        return $this->hasMany(Video::class);
    }
}

app/Comentario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comentario extends Model
{
    //
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public function commentable(){
        return $this->morphTo();
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    public function users(){
        return $this->belongsToMany(User::class)->withTimestamps();
    }
}

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    public function imageable(){
        return $this->morphTo();
    }
}

app/Level.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    public function users(){
        //Un nivel tiene muchos usuarios
        return $this->hasMany(Users::class);
    }

    public function posts(){
        //Un nivel tiene muchos posts a travez de usuarios
        return $this->hasManyThrough(Post::class, User::class);
    }

    public function videos(){
        //Un nivel tiene muchos videos a travez de usuarios
        return $this->hasManyThrough(Video::class, User::class);
    }
}

app/Location.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    //
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public function user(){
        //Un post Pertenece a un usuario
        return $this->belongsTo(User::class);
    }
    
    public function category(){
        //Un post Pertenece a una categoria
        return $this->belongsTo(Category::class);
    }

    public function comments(){
        //La palabra commentable es la que se uso en la creacion de la migracion de la tabla comment
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function image(){
        return $this->morphOne(Image::class, 'imageable');
    }

    public function tags(){
        return $this->morphToMany(Tag::class, 'taggable');
    }

}

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    public function location(){
        //Un perfil tiene una localizacion
        return $this->hasOne(Location::class);
    }
}

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts(){
        //Una etiqueta tiene muchos post
        return $this->morphedByMany(Post::class, 'taggable');
    }

    public function videos()
    {
        return $this->morphedByMany(Video::class, 'taggable');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile(){
        //Un usuario tiene un solo perfil
        return $this->hasOne(Profile::class);
    }

    public function level(){
        //Un usuario pertenece a un nivel
        return $this->belongsTo(Level::class);
    }

    public function groups(){
        //Un usuario pertenece y tiene muchos grupos
        return $this->belongsToMany(Group::class)->withTimestamps();
    }

    public function location(){
        //Un usuario tiene una localizacion a travez de perfil
        return $this->hasOneThrough(Location::class, Profile::class);
    }

    public function posts(){
        //Un usuario tiene muchos posts
        return $this->hasMany(Post::class);
    }
    
    public function videos(){
        //Un usuario tiene muchos videos
        return $this->hasMany(Video::class);
    }

    public function image(){
        return $this->morphOne(Image::class, 'imageable');
    }
}

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    public function user(){
        //Un post Pertenece a un usuario
        return $this->belongsTo(User::class);
    }

    public function category(){
        //Un post Pertenece a una categoria
        return $this->belongsTo(Category::class);
    }

    public function comments(){
        //La palabra commentable es la que se uso en la creacion de la migracion de la tabla comment
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function image(){
        //Un video tiene y pertenece a una imagen
        return $this->morphOne(Image::class, 'imageable');
    }

    public function tags(){
        //Un video tiene y pertenece a muchos tags
        return $this->morphToMany(Tag::class, 'taggable');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/level.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Usuarios de {{ $level->name }}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-12 my-3 pt-3 shadow">
                    <h1>Contenido de usuarios nivel {{ $level->name }}</h1>
					<hr>
                    <div class="row">
                        @foreach($posts as $post)
                        <div class="col-6">
                            <div class="card mb-3">
                                <div class="row no-gutters">
                                    <div class="col-md-4">
                                        <img src="{{ $post->image->url }}" class="card-img">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ $post->name }}</h5>
                                            <h6 class="card-subtitle text-muted">
                                                {{ $post->category->name }} |
                                                {{ $post->comments_count }}
                                                {{ Str::plural('comentario', $post->comments_count) }}
                                            </h6>
                                            <p class="card-text small">
                                                @foreach($post->tags as $tag)
                                                <span class="badge badge-light">
                                                    #{{ $tag->name }}
                                                </span>
                                                @endforeach
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>

                    <h1>Contenido en video de usuarios nivel {{ $level->name }}</h1>
					<hr>

                    <div class="row">
                        @foreach($videos as $video)
                        <div class="col-6">
                            <div class="card mb-3">
                                <div class="row no-gutters">
                                    <div class="col-md-4">
                                        <img src="{{ $video->image->url }}" class="card-img">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ $video->name }}</h5>
                                            <h6 class="card-subtitle text-muted">
                                                {{ $video->category->name }} |
                                                {{ $video->comments_count }}
                                                {{ Str::plural('comentario', $video->comments_count) }}
                                            </h6>
                                            <p class="card-text small">
                                                @foreach($video->tags as $tag)
                                                <span class="badge badge-light">
                                                    #{{ $tag->name }}
                                                </span>
                                                @endforeach
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
            	</div>
            </div>
        </div>
    </body>
</html>

resources/views/profile.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{{ $user->name }}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-12 my-3 pt-3 shadow">
                    <img src="{{ $user->image->url }}" alt="" class="float-left rounded-circle mr-2">
                    <h1>{{ $user->name }}</h1>
                    <h3>{{ $user->email }}</h3>
                    <p>
                        <b>Instagram: </b>{{ $user->profile->instagram }}<br>
                        <b>GitHub: </b>{{ $user->profile->github }}<br>
                        <b>Web: </b>{{ $user->profile->web }}
                    </p>
                    <p>
                        <b>País:</b>{{ $user->location->country }}<br>
                        <strong>Nivel</strong>: @if ($user->level) 
                            <a href="{{ route('level', $user->level->id) }}">
                                {{ $user->level->name }}
                            </a>
                        @else
                            ---
                        @endif <br>
                    </p>
                    <hr>
                    <p>
                        <b>Grupos:</b>
                        @forelse ($user->groups as $group)
                            <span class="badge badge-primary">{{ $group->name }}</span>
                        @empty
                            <em>No pertenece a ningun grupo</em>
                        @endforelse
                    </p>
                    <hr>
                    
                    <h3>Posts</h3>

                    <div class="row">
                        @foreach($posts as $post)
                        <div class="col-6">
                            <div class="card mb-3">
                                <div class="row no-gutters">
                                    <div class="col-md-4">
                                        <img src="{{ $post->image->url }}" class="card-img">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ $post->name }}</h5>
                                            <h6 class="card-subtitle text-muted">
                                                {{ $post->category->name }} |
                                                {{ $post->comments_count }}
                                                {{ Str::plural('comentario', $post->comments_count) }}
                                            </h6>
                                            <p class="card-text small">
                                                @foreach($post->tags as $tag)
                                                <span class="badge badge-light">
                                                    #{{ $tag->name }}
                                                </span>
                                                @endforeach
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>

                     <h3>Videos</h3>

                    <div class="row">
                        @foreach($videos as $video)
                        <div class="col-6">
                            <div class="card mb-3">
                                <div class="row no-gutters">
                                    <div class="col-md-4">
                                        <img src="{{ $video->image->url }}" class="card-img">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ $video->name }}</h5>
                                            <h6 class="card-subtitle text-muted">
                                                {{ $video->category->name }} |
                                                {{ $video->comments_count }}
                                                {{ Str::plural('comentario', $video->comments_count) }}
                                            </h6>
                                            <p class="card-text small">
                                                @foreach($video->tags as $tag)
                                                <span class="badge badge-light">
                                                    #{{ $tag->name }}
                                                </span>
                                                @endforeach
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>